### ISSUE TITLE
Weather for Upcoming week.

### ISSUE THREAD

**Issue by dhruvpatel1706** [clubgamma/Weather-Forecaster#2]
- The feature should be designed in such a way that it displays the weather for the upcoming week.

**Comment by Yashdew** [comment]
@dhruvpatel1706 @jayskhatri take a look into my PR.

**Comment by Yashdew** [comment]
> @dhruvpatel1706 @jayskhatri take a look into my PR.

@yashpaneliya

**Comment by Yashdew** [comment]
@yashpaneliya any updates?
